[tasks]
bot = "uv run python -m bot -c config.local.yaml"
build = """
docker buildx build --pull --push \
--platform linux/amd64 \
-t lax.vultrcr.com/mercury/korg:latest \
-t lax.vultrcr.com/mercury/korg:{{ exec(command='uv version --short') }} .
"""

upgrade = """
kubectl apply -k k8s --server-side && \
kubectl -n misskey rollout restart deployment grok
"""

[env]
_.python.venv = ".venv"

[tools]
ruff = "latest"
uv = "latest"
