# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- base.yaml
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
- name: grok-config
  namespace: misskey
  files:
  - config.yaml=config.yaml
  - optimized.json=optimized.json
  options:
    labels:
      app.kubernetes.io/name: grok
secretGenerator:
- name: grok-secrets
  namespace: misskey
  envs:
  - secrets.txt
  options:
    labels:
      app.kubernetes.io/name: grok
